// App User Auth State Machine
export const SET_APP_USER = 'SET_APP_USER';
export const RESET_USER = 'RESET_USER';

// Sign In State Machine
export const BEGIN_AUTHENTICATION = 'BEGIN_AUTHENTICATION';
export const START_SIGN_IN_ASYNC = 'START_SIGN_IN_ASYNC';
export const SET_AUTHENTICATION_SUCCESSFUL = 'SET_AUTHENTICATION_SUCCESSFUL';
export const SET_AUTHENTICATION_FAILED = 'SET_AUTHENTICATION_FAILED';
// Facebook Sign In State Machine
export const START_SIGN_IN_ASYNC_FACEBOOK = 'START_SIGN_IN_ASYNC_FACEBOOK';
